export const locale: Record<string, string> = {
  'General Fields': 'General Fields',
  Delete: 'Delete',
  Edit: 'Edit',
  Copy: 'Copy',
  Move: 'Move',
  Step: 'Step',
  'Insert Field': 'Insert Field',
  'Insert General Field': 'Insert General Field',
  'Insert Conditional Logic Block': 'Insert Conditional Logic Block',
  'Save Conditional Logic Blocks Data': 'Save Conditional Logic Blocks Data',
  'Previous Step': 'Previous Step',
  'Next Step': 'Next Step',
  Save: 'Save',
  Cancel: 'Cancel',
  'Go to': 'Go to',
  'Move step': 'Move step',
  'Copy step': 'Copy step',
  'Delete step': 'Delete step',
  Country: 'Country',
  'Text Input': 'Text Input',
  'Text Area': 'Text Area',
  Date: 'Date',
  Select: 'Select',
  Number: 'Number',
  Checkbox: 'Checkbox',
  Checkboxes: 'Checkboxes',
  Radio: 'Radio',
  'File Attachment': 'File Attachment',
  Password: 'Password',
  Email: 'Email',
  'Phone Number': 'Phone Number',
  'Likert Scale': 'Likert Scale',
  'CSAT Scale': 'CSAT Scale',
  'CES Scale': 'CES Scale',
  'NPS Scale': 'NPS Scale',
  'QE Group': 'QE Group',
  'Need Contact': 'Need Contact',
  'Contact Name': 'Contact Name',
  'Contact Surname': 'Contact Surname',
  'Contact Email': 'Contact Email',
  'Contact Phone': 'Contact Phone',
  'Select a type of Field': 'Select a type of Field',
  'Add Options': 'Add Options',
  'Edit Field Properties': 'Edit Field Properties',
  Active: 'Active',
  Classes: 'Classes',
  Placeholder: 'Placeholder',
  Title: 'Title',
  Description: 'Description',
  Validators: 'Validators',
  Required: 'Required',
  'Warning message': 'Warning message',
  'Analytics title': 'Analytics title',
  'Move to step': 'Move to step',
  'Select a validator': 'Select a validator',
  Value: 'Value',
  'Error Message': 'Error Message',
  'Remove Validator': 'Remove Validator',
  'Add Validator': 'Add Validator',
  'Option Text': 'Option Text',
  'Option Value': 'Option Value',
  'Option Country': 'Option Country',
  'Remove Option': 'Remove Option',
  'Add Option': 'Add Option',
  'Comment title': 'Comment title',
  'Comment subtitle': 'Comment subtitle',
  'Comment warning message': 'Comment warning message',
  'Remove Comment': 'Remove Comment',
  'Add Comment': 'Add Comment',
  'QE Scale Title': 'QE Scale Title',
  'QE Scale Subtitle': 'QE Scale Subtitle',
  'QE Scale Child Title': 'QE Scale Child Title',
  'Remove QE Scale Child': 'Remove QE Scale Child',
  'Remove QE Scale': 'Remove QE Scale',
  'Add QE Scale Child': 'Add QE Scale Child',
  'Add QE Scale': 'Add QE Scale',
  'Row Title': 'Row Title',
  'Remove Row': 'Remove Row',
  'Add Row': 'Add Row',
  'Add Step': 'Add Step',
  'Remove Step': 'Remove Step',
  'Select Step': 'Select Step',
  Yes: 'Yes',
  No: 'No',
  'Default Value': 'Default Value',
  'Remove Warning Message': 'Remove Warning Message',
  'Has Other': 'Has Other',
  'Has NA': 'Has NA',
  'Warning Message': 'Warning Message',
  'Move Row': 'Move Row',
  'Are you sure you want to complete field creation without saving?':
    'Are you sure you want to complete field creation without saving?',
  'Are you sure you want to delete this step?': 'Are you sure you want to delete this step?',
  'Please fill in all required fields': 'Please fill in all required fields',
  'Use this field when creating feedback text': 'Use this field when creating feedback text',
  Feedback: 'Feedback'
};
